package com.zhub.servicemaster.models;
// Generated Nov 27, 2017 2:54:40 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * KeyTable generated by hbm2java
 */
public class KeyTable  implements java.io.Serializable {


     private Integer keyId;
     private String keyCode;
     private Integer keyNumber;
     private String keyRemark;
     private Integer isActive;
     private Date createdDate;
     private Date createdTime;
     private Integer createdUser;
     private Date modifiedDate;
     private Date modifiedTime;
     private Integer modifiedUser;

    public KeyTable() {
    }

    public KeyTable(String keyCode, Integer keyNumber, String keyRemark, Integer isActive, Date createdDate, Date createdTime, Integer createdUser, Date modifiedDate, Date modifiedTime, Integer modifiedUser) {
       this.keyCode = keyCode;
       this.keyNumber = keyNumber;
       this.keyRemark = keyRemark;
       this.isActive = isActive;
       this.createdDate = createdDate;
       this.createdTime = createdTime;
       this.createdUser = createdUser;
       this.modifiedDate = modifiedDate;
       this.modifiedTime = modifiedTime;
       this.modifiedUser = modifiedUser;
    }
   
    public Integer getKeyId() {
        return this.keyId;
    }
    
    public void setKeyId(Integer keyId) {
        this.keyId = keyId;
    }
    public String getKeyCode() {
        return this.keyCode;
    }
    
    public void setKeyCode(String keyCode) {
        this.keyCode = keyCode;
    }
    public Integer getKeyNumber() {
        return this.keyNumber;
    }
    
    public void setKeyNumber(Integer keyNumber) {
        this.keyNumber = keyNumber;
    }
    public String getKeyRemark() {
        return this.keyRemark;
    }
    
    public void setKeyRemark(String keyRemark) {
        this.keyRemark = keyRemark;
    }
    public Integer getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    public Integer getCreatedUser() {
        return this.createdUser;
    }
    
    public void setCreatedUser(Integer createdUser) {
        this.createdUser = createdUser;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public Date getModifiedTime() {
        return this.modifiedTime;
    }
    
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
    public Integer getModifiedUser() {
        return this.modifiedUser;
    }
    
    public void setModifiedUser(Integer modifiedUser) {
        this.modifiedUser = modifiedUser;
    }




}


