package com.zhub.servicemaster.models;
// Generated Nov 27, 2017 2:54:40 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SaleItem generated by hbm2java
 */
public class SaleItem  implements java.io.Serializable {


     private Integer id;
     private Item item;
     private Sale sale;
     private SaleItemStatus saleItemStatus;
     private Float unitPrice;
     private Float quantity;
     private Float subTotal;
     private Float discount;
     private Float total;
     private Integer isActive;
     private Date createdDate;
     private Date createdTime;
     private Integer createdUser;
     private Date modifiedDate;
     private Date modifiedTime;
     private Integer modifiedUser;
     private String remark;

    public SaleItem() {
    }

	
    public SaleItem(Item item, Sale sale, SaleItemStatus saleItemStatus) {
        this.item = item;
        this.sale = sale;
        this.saleItemStatus = saleItemStatus;
    }
    public SaleItem(Item item, Sale sale, SaleItemStatus saleItemStatus, Float unitPrice, Float quantity, Float subTotal, Float discount, Float total, Integer isActive, Date createdDate, Date createdTime, Integer createdUser, Date modifiedDate, Date modifiedTime, Integer modifiedUser, String remark) {
       this.item = item;
       this.sale = sale;
       this.saleItemStatus = saleItemStatus;
       this.unitPrice = unitPrice;
       this.quantity = quantity;
       this.subTotal = subTotal;
       this.discount = discount;
       this.total = total;
       this.isActive = isActive;
       this.createdDate = createdDate;
       this.createdTime = createdTime;
       this.createdUser = createdUser;
       this.modifiedDate = modifiedDate;
       this.modifiedTime = modifiedTime;
       this.modifiedUser = modifiedUser;
       this.remark = remark;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public Sale getSale() {
        return this.sale;
    }
    
    public void setSale(Sale sale) {
        this.sale = sale;
    }
    public SaleItemStatus getSaleItemStatus() {
        return this.saleItemStatus;
    }
    
    public void setSaleItemStatus(SaleItemStatus saleItemStatus) {
        this.saleItemStatus = saleItemStatus;
    }
    public Float getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Float unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Float getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Float quantity) {
        this.quantity = quantity;
    }
    public Float getSubTotal() {
        return this.subTotal;
    }
    
    public void setSubTotal(Float subTotal) {
        this.subTotal = subTotal;
    }
    public Float getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Float discount) {
        this.discount = discount;
    }
    public Float getTotal() {
        return this.total;
    }
    
    public void setTotal(Float total) {
        this.total = total;
    }
    public Integer getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    public Integer getCreatedUser() {
        return this.createdUser;
    }
    
    public void setCreatedUser(Integer createdUser) {
        this.createdUser = createdUser;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public Date getModifiedTime() {
        return this.modifiedTime;
    }
    
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
    public Integer getModifiedUser() {
        return this.modifiedUser;
    }
    
    public void setModifiedUser(Integer modifiedUser) {
        this.modifiedUser = modifiedUser;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }




}


