/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zhub.servicemaster.internalFrames;

import com.zhub.servicemaster.accounts.PostAccounts;
import com.zhub.servicemaster.data.SystemData;
import com.zhub.servicemaster.dialogs.InformationDialog;
import com.zhub.servicemaster.functions.AutoCompletion;
import com.zhub.servicemaster.functions.LimitDocumentFilter;
import com.zhub.servicemaster.guiFunctions.ButtonFunctions;
import com.zhub.servicemaster.models.Account;
import com.zhub.servicemaster.models.Bank;
import com.zhub.servicemaster.models.BusinessPartner;
import com.zhub.servicemaster.utils.HibernateUtil;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.List;
import java.util.TreeMap;
import javax.swing.SwingUtilities;
import javax.swing.text.AbstractDocument;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.criterion.Order;
import org.hibernate.criterion.Restrictions;

/**
 *
 * @author RuwanM
 */
public class ChequeReceipt extends javax.swing.JInternalFrame {

    /**
     * Creates new form ChequeReceipt
     */
    public ChequeReceipt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbCustomer = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbBank = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        dateChequeDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txtChequeNumber = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbBankAccount = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtPaidAmount = new javax.swing.JFormattedTextField();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cheque Receipts");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        cmbCustomer.setEditable(true);
        cmbCustomer.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setText("Bank :");

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel10.setText("Customer :");

        cmbBank.setEditable(true);
        cmbBank.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setText("Cheque No :");

        dateChequeDate.setDate(new Date());
        dateChequeDate.setDateFormatString("yyyy-MM-dd");
        dateChequeDate.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        dateChequeDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dateChequeDateKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("Amount :");

        txtChequeNumber.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtChequeNumber.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtChequeNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtChequeNumberKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setText("Cheque Date :");

        cmbBankAccount.setEditable(true);
        cmbBankAccount.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel9.setText("Bank Account :");

        txtPaidAmount.setBackground(new java.awt.Color(255, 255, 255));
        txtPaidAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.0"))));
        txtPaidAmount.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtPaidAmount.setText("0.0");
        txtPaidAmount.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtPaidAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPaidAmountFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPaidAmount))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCustomer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtChequeNumber))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateChequeDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbBank, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbBankAccount, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel2, jLabel6, jLabel7, jLabel8, jLabel9});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPaidAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtChequeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(dateChequeDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbBankAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbBank, cmbBankAccount, cmbCustomer, dateChequeDate, jLabel10, jLabel2, jLabel6, jLabel7, jLabel8, jLabel9, txtChequeNumber, txtPaidAmount});

        btnSave.setBackground(new java.awt.Color(150, 255, 150));
        btnSave.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 255, 50)));
        btnSave.setContentAreaFilled(false);
        btnSave.setOpaque(true);
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveMouseExited(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(150, 255, 150));
        btnClose.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnClose.setText("Close");
        btnClose.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 255, 50)));
        btnClose.setContentAreaFilled(false);
        btnClose.setOpaque(true);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtChequeNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChequeNumberKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String text = txtChequeNumber.getText();
            if (!text.isEmpty()) {
                dateChequeDate.requestFocus();
            }
        } else {
            if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
                String value = txtChequeNumber.getText();
                ((AbstractDocument) txtChequeNumber.getDocument()).setDocumentFilter(new LimitDocumentFilter(15));
                if (value.length() == 6
                        || value.length() == 11) {
                    value += "-";
                    txtChequeNumber.setText(value);
                }
            }
        }
    }//GEN-LAST:event_txtChequeNumberKeyReleased

    private void dateChequeDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateChequeDateKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cmbBank.requestFocus();
        }
    }//GEN-LAST:event_dateChequeDateKeyPressed

    private void btnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseEntered
        ButtonFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_ENTER_COLOR);
    }//GEN-LAST:event_btnSaveMouseEntered

    private void btnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseExited
        ButtonFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_EXIT_COLOR);
    }//GEN-LAST:event_btnSaveMouseExited

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (this.validateForm()) {
            String customer = cmbCustomer.getSelectedItem().toString();
            String chequeNumber = txtChequeNumber.getText().trim();
            Date chequeDate = dateChequeDate.getDate();
            float amount = Float.parseFloat(txtPaidAmount.getText().trim());

            Session session = HibernateUtil.getSessionFactory().openSession();
            Transaction transaction = session.beginTransaction();

            String customerCode = this.customerMap.get(customer);
            BusinessPartner businessPartner = (BusinessPartner) session
                    .createCriteria(BusinessPartner.class)
                    .add(Restrictions.eq("businessPartnerCode", customerCode))
                    .uniqueResult();

            Account cihAccount = (Account) session
                    .createCriteria(Account.class)
                    .add(Restrictions.eq("accountCode", "ACC1004"))
                    .uniqueResult();

            Account uarAccount = (Account) session
                    .createCriteria(Account.class)
                    .add(Restrictions.eq("accountCode", "ACC1006"))
                    .uniqueResult();

            transaction.commit();
            session.close();

            PostAccounts accountPosting = new PostAccounts();
            accountPosting.chequeDebitPosting(cihAccount, businessPartner, null, amount, chequeDate, 0, chequeNumber, "Cheque receipt from " + businessPartner.getFirstName() + " " + businessPartner.getLastName());
            accountPosting.chequeCreditPosting(uarAccount, businessPartner, null, amount, chequeDate, 0, chequeNumber, "Cheque receipt from " + businessPartner.getFirstName() + " " + businessPartner.getLastName());

            InformationDialog.showMessageBox("Saved successfilly", "Saved", this);
        } else {
            InformationDialog.showMessageBox("Please fill valid data.", "Invalid", this);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        ButtonFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_ENTER_COLOR);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        ButtonFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_EXIT_COLOR);
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        Session session = HibernateUtil.getSessionFactory().openSession();

        List<Account> accounts = session
                .createCriteria(Account.class)
                .createAlias("subAccount", "subAccount")
                .add(Restrictions.eq("subAccount.code", "SAC1001"))
                .list();

        if (!accounts.isEmpty()) {
            cmbBankAccount.removeAllItems();
            cmbBankAccount.addItem("");
            for (Account account : accounts) {
                cmbBankAccount.addItem(account.getDescription());
            }
        }

        List<Bank> banks = session
                .createCriteria(Bank.class)
                .addOrder(Order.asc("id"))
                .list();

        if (!banks.isEmpty()) {
            cmbBank.removeAllItems();
            cmbBank.addItem("");
            for (Bank bank : banks) {
                cmbBank.addItem(bank.getBankName());
            }
        }

        List<BusinessPartner> businessPartners = session
                .createCriteria(BusinessPartner.class)
                .add(Restrictions.eq("isCustomer", true))
                .list();
        if (!businessPartners.isEmpty()) {
            cmbCustomer.removeAllItems();
            cmbCustomer.addItem("");
            for (BusinessPartner businessPartner : businessPartners) {
                cmbCustomer.addItem(businessPartner.getFirstName() + " " + businessPartner.getLastName());
                this.customerMap.put(businessPartner.getFirstName() + " " + businessPartner.getLastName(), businessPartner.getBusinessPartnerCode());
            }
        }

        session.close();

        AutoCompletion.enable(cmbCustomer, txtChequeNumber);
        AutoCompletion.enable(cmbBank, cmbBankAccount);
        AutoCompletion.enable(cmbBankAccount, btnSave);
    }//GEN-LAST:event_formInternalFrameOpened

    private void txtPaidAmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaidAmountFocusGained
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                txtPaidAmount.selectAll();
            }
        });
    }//GEN-LAST:event_txtPaidAmountFocusGained

    private boolean validateForm() {
        float nowPaying = Float.parseFloat(txtPaidAmount.getText().trim());
        String customer = cmbCustomer.getSelectedItem().toString().trim();
        String chequeNumber = txtChequeNumber.getText().trim();
        String bank = cmbBank.getSelectedItem().toString().trim();
        String bankAccount = cmbBankAccount.getSelectedItem().toString().trim();
        return !(nowPaying == 0.0f
                || customer.isEmpty()
                || chequeNumber.isEmpty()
                || bank.isEmpty()
                || bankAccount.isEmpty());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    public javax.swing.JComboBox<String> cmbBank;
    public javax.swing.JComboBox<String> cmbBankAccount;
    public javax.swing.JComboBox<String> cmbCustomer;
    public com.toedter.calendar.JDateChooser dateChequeDate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JFormattedTextField txtChequeNumber;
    public javax.swing.JFormattedTextField txtPaidAmount;
    // End of variables declaration//GEN-END:variables
    public TreeMap<String, String> customerMap = new TreeMap<>();
}
