/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zhub.servicemaster.internalFrames;

import com.zhub.servicemaster.data.SystemData;
import com.zhub.servicemaster.dialogs.InformationDialog;
import com.zhub.servicemaster.guiFunctions.ButtonFunctions;
import com.zhub.servicemaster.models.BusinessAddress;
import com.zhub.servicemaster.models.Invoice;
import com.zhub.servicemaster.models.Sale;
import com.zhub.servicemaster.models.SaleItem;
import com.zhub.servicemaster.models.SaleStatus;
import com.zhub.servicemaster.models.Vehicle;
import com.zhub.servicemaster.utils.HibernateUtil;
import java.awt.Color;
import java.awt.Component;
import java.beans.PropertyVetoException;
import java.util.List;
import java.util.Set;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import org.hibernate.Criteria;
import org.hibernate.Hibernate;
import org.hibernate.Session;
import org.hibernate.criterion.Restrictions;

/**
 *
 * @author RuwanM
 */
public class ServicesFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form SeviceFrame
     */
    public ServicesFrame() {
        initComponents();

        DefaultListModel<String> listModel = new DefaultListModel<>();
        listModel.addElement("No services available");
        listServices.setModel(listModel);
        listServices.setCellRenderer(this.getListCellRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JToolBar();
        toolbarPanel = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        splitPane = new javax.swing.JSplitPane();
        desktopPane = new javax.swing.JDesktopPane();
        existServicePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listServices = new javax.swing.JList<>();
        btnOpen = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Services");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        toolbar.setFloatable(false);
        toolbar.setRollover(true);

        toolbarPanel.setMaximumSize(new java.awt.Dimension(32767, 35));
        toolbarPanel.setOpaque(false);
        toolbarPanel.setPreferredSize(new java.awt.Dimension(782, 35));

        btnSave.setBackground(new java.awt.Color(150, 255, 150));
        btnSave.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnSave.setText("New Service");
        btnSave.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 255, 50)));
        btnSave.setContentAreaFilled(false);
        btnSave.setOpaque(true);
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveMouseExited(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toolbarPanelLayout = new javax.swing.GroupLayout(toolbarPanel);
        toolbarPanel.setLayout(toolbarPanelLayout);
        toolbarPanelLayout.setHorizontalGroup(
            toolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolbarPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(687, Short.MAX_VALUE))
        );
        toolbarPanelLayout.setVerticalGroup(
            toolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolbarPanelLayout.createSequentialGroup()
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        toolbar.add(toolbarPanel);

        splitPane.setDividerLocation(100);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(desktopPane);

        listServices.setBackground(new java.awt.Color(150, 255, 150));
        listServices.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        listServices.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listServices.setSelectionBackground(new java.awt.Color(50, 255, 50));
        listServices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listServicesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listServices);

        btnOpen.setBackground(new java.awt.Color(150, 255, 150));
        btnOpen.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnOpen.setText("Open");
        btnOpen.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 255, 50)));
        btnOpen.setContentAreaFilled(false);
        btnOpen.setOpaque(true);
        btnOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOpenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOpenMouseExited(evt);
            }
        });
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout existServicePanelLayout = new javax.swing.GroupLayout(existServicePanel);
        existServicePanel.setLayout(existServicePanelLayout);
        existServicePanelLayout.setHorizontalGroup(
            existServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
            .addComponent(btnOpen, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
        );
        existServicePanelLayout.setVerticalGroup(
            existServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(existServicePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        splitPane.setLeftComponent(existServicePanel);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        this.loadServices();
    }//GEN-LAST:event_formInternalFrameOpened

    private void listServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listServicesMouseClicked
        if (evt.getClickCount() == 2) {
            this.openService();
        }
    }//GEN-LAST:event_listServicesMouseClicked

    private void btnOpenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenMouseEntered
        ButtonFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_ENTER_COLOR);
    }//GEN-LAST:event_btnOpenMouseEntered

    private void btnOpenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenMouseExited
        ButtonFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_EXIT_COLOR);
    }//GEN-LAST:event_btnOpenMouseExited

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        if (listServices.getSelectedValue() != null) {
            this.openService();
        } else {
            InformationDialog.showMessageBox("Please select a valid vehicle.", "Invalid", null);
        }
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseEntered
        ButtonFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_ENTER_COLOR);
    }//GEN-LAST:event_btnSaveMouseEntered

    private void btnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseExited
        ButtonFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_EXIT_COLOR);
    }//GEN-LAST:event_btnSaveMouseExited

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            if (this.serviceFrame != null) {
                JOptionPane.showMessageDialog(this, "Please save and close opened service.", "Close", JOptionPane.INFORMATION_MESSAGE);
            } else {
                this.serviceFrame = new ServiceFrame(null, this);
                desktopPane.add(serviceFrame);
                serviceFrame.setMaximum(true);

                BasicInternalFrameUI internalFrameUI = (BasicInternalFrameUI) serviceFrame.getUI();
                internalFrameUI.setNorthPane(null);
                serviceFrame.setBorder(null);

                serviceFrame.setVisible(true);
            }
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ServicesFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    public void loadServices() {
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();

        Criteria serviceCriteria = session.createCriteria(Sale.class);
        
        serviceCriteria.add(Restrictions.ne("saleStatus", session.load(SaleStatus.class, new SaleStatus(4).getStatusId())));
        serviceCriteria.add(Restrictions.ne("saleStatus", session.load(SaleStatus.class, new SaleStatus(5).getStatusId())));
        serviceCriteria.add(Restrictions.ne("saleStatus", session.load(SaleStatus.class, new SaleStatus(6).getStatusId())));
        serviceCriteria.add(Restrictions.ne("saleStatus", session.load(SaleStatus.class, new SaleStatus(7).getStatusId())));

        List list = serviceCriteria.list();

        DefaultListModel<String> listModel = (DefaultListModel<String>) listServices.getModel();
        listModel.clear();

        if (!list.isEmpty()) {
            for (Object object : list) {
                if (object instanceof Sale) {
                    Sale sale = (Sale) object;
                    Vehicle vehicle = sale.getVehicle();

                    Hibernate.initialize(vehicle.getBusinessPartner());
                    Hibernate.initialize(sale.getServiceBay());
                    Hibernate.initialize(sale.getVehicle());
                    Hibernate.initialize(sale.getSaleStatus());

                    Set addresses = vehicle.getBusinessPartner().getBusinessAddresses();
                    for (Object tempAddresse : addresses) {
                        if (tempAddresse instanceof BusinessAddress) {
                            BusinessAddress businessAddress = (BusinessAddress) tempAddresse;
                            Hibernate.initialize(businessAddress.getAddress());
                        }
                    }

                    Set saleItems = sale.getSaleItems();
                    for (Object tempSaleItem : saleItems) {
                        if (tempSaleItem instanceof SaleItem) {
                            SaleItem saleItem = (SaleItem) tempSaleItem;
                            Hibernate.initialize(saleItem);
                            Hibernate.initialize(saleItem.getItem());
                        }
                    }

                    Set invoices = sale.getInvoices();
                    for (Object tempInvoice : invoices) {
                        if (tempInvoice instanceof Invoice) {
                            Invoice invoice = (Invoice) tempInvoice;
                            Hibernate.initialize(invoice);
                        }
                    }

                    listModel.addElement(vehicle.getVehicleNumber());
                    saleMap.put(vehicle.getVehicleNumber(), sale);
                }
            }
        }

        session.close();
    }

    private void openService() {
        try {
            String value = listServices.getSelectedValue();
            Sale sale = saleMap.get(value);

            if (serviceFrame != null) {
                serviceFrame.dispose();
            }
            this.serviceFrame = new ServiceFrame(sale, this);
            desktopPane.add(serviceFrame);
            serviceFrame.setMaximum(true);

            BasicInternalFrameUI internalFrameUI = (BasicInternalFrameUI) serviceFrame.getUI();
            internalFrameUI.setNorthPane(null);
            serviceFrame.setBorder(null);

            serviceFrame.setVisible(true);
            listServices.clearSelection();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(ServicesFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private ListCellRenderer<? super String> getListCellRenderer() {
        return new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list,
                    Object value, int index, boolean isSelected,
                    boolean cellHasFocus) {
                JLabel listCellRendererComponent = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                listCellRendererComponent.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(50, 255, 50)));
                return listCellRendererComponent;
            }
        };
    }

    public void setServiceFrame(ServiceFrame serviceFrame) {
        this.serviceFrame = serviceFrame;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSave;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JPanel existServicePanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listServices;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JToolBar toolbar;
    private javax.swing.JPanel toolbarPanel;
    // End of variables declaration//GEN-END:variables
    private final TreeMap<String, Sale> saleMap = new TreeMap<>();
    private ServiceFrame serviceFrame;
}
